vim.keymap.set("n", "<leader>a", ":set autochdir<CR>")
vim.keymap.set("n", "<leader>h", ":set nohlsearch<CR>")
vim.keymap.set("n", "|", ":vsplit<CR>")
vim.keymap.set("n", "-", ":split<CR>")
vim.keymap.set("n", "Q", ":bprevious<CR>")
vim.keymap.set("n", "E", ":bnext<CR>")
vim.keymap.set("n", "<leader>w", ":w<CR>")
vim.keymap.set("n", "<leader>q", ":bd<CR>")
vim.keymap.set("n", "<leader>Q", ":bd!<CR>")
